{% set name = "pytest-ordering" %}
{% set version = "6.0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://github.com/ftobia/{{ name }}/archive/{{ version }}.tar.gz"
  sha256: d5558cd419c8d46bdc958064cb97f963d1ea793866414c025906ec15033512ed

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - pytest
    - python
    - setuptools
  run:
    - pytest
    - python

test:
  imports:
    - pytest_ordering

about:
  home: "https://github.com/ftobia/pytest-ordering"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "pytest plugin to run your tests in a specific order"

extra:
  recipe-maintainers:
    - jni
